site_name: BotsOnRails
site_url: https://jsv4.github.io/BotsOnRails/
nav:
  - Home: about.md
  - Index: index.md
  - Quickstart: quickstart.md
  - Syntax Guide: node_syntax.md
  - Resume: resumable_workflows.md
  - Type Checking: validation.md
  - Loops: loops.md
theme: readthedocs